### ISSUE TITLE
DNS Autodiscover on Linux is not working

### ISSUE THREAD

**Issue by sherlock1982** [sherlock1982/ews-managed-api#1]
The last algorithm for Autodiscover is made with DNS Autodiscover. On Linux it fails with a message "Unable to load DLL 'dnsapi.dll".  For now it should be treated as "Autodiscover failed".

Need to find a way to do DNS Autodiscover on Linux or just don't call it at all.

**Comment by lgkonline** [comment]
In my case I wanted to receive calendar data and I handled it this way:

                ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2007_SP1);
                service.Credentials = new WebCredentials(exchangeUser, exchangePassword);
                service.Url = new Uri(exchangeUri);

                DateTime startDate = DateTime.Today.AddSeconds(1);
                DateTime endDate = startDate.AddHours(23).AddMinutes(59).AddSeconds(58);

                string calendarFolderId = folderId;

                CalendarFolder calendar = ((System.Threading.Tasks.Task<CalendarFolder>)CalendarFolder.Bind(service, calendarFolderId, new PropertySet())).Result;

                CalendarView cView = new CalendarView(startDate, endDate);
                cView.PropertySet = new PropertySet(AppointmentSchema.Subject, AppointmentSchema.Start, AppointmentSchema.End);

                FindItemsResults<Appointment> appointments = ((System.Threading.Tasks.Task<FindItemsResults<Appointment>>)calendar.FindAppointments(cView)).Result;

It works fine. On my Linux or Mac OS systems it does not work because of certification reasons. If the Windows server is on the same domain as the Exchange service it works.

**Comment by sherlock1982** [comment]
So it's another issue. Because of certification reasons you mean self-signed SSL certificate? If yes, than I have a fix for this but it's not yet commited,

**Comment by lgkonline** [comment]
Our Exchange only accepts requests if the server is on the same domain. So I decided to publish my code on a server which fulfill this condition.

**Comment by lukapor** [comment]
hi, here is some patch for dns autodiscover.

https://github.com/4thOffice/ews-managed-api/commit/740ad35b11d13e04dd21c6c4121acc899b90f0f9

Because dns dll is not supported in no windows platform (throws System.DllNotFoundException), is better to skip dns discover. If you have logic on login which depends on autodicover exception, to show extended login options.

**Comment by PaulDMendoza** [comment]
Have you guys tried using the DnsClient Nuget package to support the DNS auto discovery yet? That might be able to replace the current DNS limitation.

**Comment by sherlock1982** [comment]
Well frankly speaking I consider it more a note than a bug. 
DNS Autodiscover is the last step in autodiscover for on-premise systems. Last try. There are other steps which work now in NETStandard 2.0. I believe the future is in Office365 where autodiscover works. 

On the other hand Autodiscover is not what clients want I think. It's slow, might be not reliable. Just put URL and you will not need it at all :-)

**Comment by PaulDMendoza** [comment]
I ended up outsourcing the auto discovery to a Node package called "exchange-autodiscover". I setup a Lambda to run it for me. 

https://www.npmjs.com/package/exchange-autodiscover

I think it is actually better than the one that ships with EWS for the normal .NET framework because it discovers the server a lot faster since it tries all the possible URLs all at once. The normal .NET framework version of autodiscovery could take 20 - 90 seconds to discover Office 365 for a custom domain. But with this is takes about 1 second.

**Comment by ststeiger** [comment]
Just writing that you can add the (pre-release) nuget-package System.DirectoryServices/4.5.0-rc1 and re-add the file `Microsoft.Exchange.WebServices.Data\Autodiscover\DirectoryHelper.cs`

And in `Microsoft.Exchange.WebServices.Data\Autodiscover\AutodiscoverService.cs` modify the function DefaultGetScpUrlsForDomain back to its original state:
```
      /// <summary>
        /// Defaults the get autodiscover service urls for domain.
        /// </summary>
        /// <param name="domainName">Name of the domain.</param>
        /// <returns></returns>
        private ICollection<string> DefaultGetScpUrlsForDomain(string domainName)
        {
            DirectoryHelper helper = new DirectoryHelper(this);
            return helper.GetAutodiscoverScpUrlsForDomain(domainName);
        }
```
then it will work (at least on Linux - tested).

**Comment by sherlock1982** [comment]
Thanks! I will return to this package very soon!

**Comment by sherlock1982** [comment]
Duplicate of #24
