### ISSUE TITLE
Appointment creation 'stuck'

### ISSUE THREAD

**Issue by ruben-lucrasoft** [sherlock1982/ews-managed-api#13]
Hi,

When I'm creating a new appointment, it doesn't show up in my calendar. Not after refresh or logout/login.

When I retry to add the appointment it goes through including the previous attempt, resulting in a double appointment.

Hope you can help me with this.

**Comment by ruben-lucrasoft** [comment]
Found out the saving was running on a separate thread that got cut off as soon as the program stopped running. Adding .Wait() after .Save() solved my issue.

**Comment by sherlock1982** [comment]
Well async/await technique should help you to avoid creating new threads and using .Wait(). If you're using .Wait() usually you're doing something wrong because it contradicts asynchronous principle.
