### ISSUE TITLE
Method "Send" should read "SendAsync"

### ISSUE THREAD

**Issue by WhistlerHusky** [sherlock1982/ews-managed-api#15]
The method name could make user confused.

**Comment by sherlock1982** [comment]
Well I try to keep method names the same with EWS so users can use documentation, refer to samples e.t.c. Yes, I know that now almost all async and it may be a bit confusing. But than I need to change ALL public methods which I don't want.

**Comment by sherlock1982** [comment]
Look [here](https://stackoverflow.com/questions/15951774/does-the-use-of-the-async-suffix-in-a-method-name-depend-on-whether-the-async) at Steven Thoub explanation:

> Of course, there are always exceptions to a guideline. The most notable one in the case of naming would be cases where an entire type’s raison d’etre is to provide async-focused functionality, in which case having Async on every method would be overkill, e.g. the methods on Task itself that produce other Tasks.

Almost all of the methods are async so why append suffix?

**Comment by WhistlerHusky** [comment]
Last time what happened to me is that, before the program close, it calls "Send", but, as it is async method, it's done before sending the email. So I had to spend some time to figure out. In the EWS, the actual return type is 'void' I think you can add the same return type then you can change the current 'Send' method to 'SendAsync' something like that.
it's just my opinion. anyway thanks for this library ;)

**Comment by sherlock1982** [comment]
Let's do like this. Leave it open and probably we'll have some opinions on this and than we'll decide. Also keep in mind that it's a huge change in API so all of the people should adjust their apps.
