### ISSUE TITLE
Ubuntu - trouble with TimeZoneTransitionGroup

### ISSUE THREAD

**Issue by IInvocation** [sherlock1982/ews-managed-api#16]
After authenticating with EWS on Ubuntu - i can now read appointments and mails - however - i'm unable to save new Appointments due to a strange error related to TimeZones.

Executing the following code:
```
/// <summary>	Adds an appointment. </summary>
		/// <param name="appointment">	The appointment. </param>
		public async Task<EwsAppointment> AddAppointment(EwsAppointment appointment)
		{
			if (_options.DeleteMails)
				await DeleteOldMails();

			var folder = await GetFolder(_options.TargetFolder);
			var apt = new Appointment(_service)
			{
				Subject = appointment.Subject,
				Body = appointment.Body,
				Start = appointment.Start,
				End = appointment.End,
				Location = appointment.Location,
				IsAllDayEvent = appointment.IsAllDay
			};

			foreach (var attendee in appointment.Attendees)
				apt.RequiredAttendees.Add(attendee);

			await apt.Save(folder, SendInvitationsMode.SendToNone);
			return appointment;
		}
```
throws an ArgumentException that seems to be raised whenever the class "ExchangeServiceBase" get's is TimeZoneDefinition.

The Stracktrace is as follows:

> 2017-11-10 12:48:49.810 +01:00 [Error] Unhandled exception
> System.ArgumentException: An item with the same key has already been added. Key: Dlt/1916
>    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at Microsoft.Exchange.WebServices.Data.TimeZoneTransitionGroup.InitializeFromAdjustmentRule(AdjustmentRule adjustmentRule, TimeZonePeriod standardPeriod)
>    at Microsoft.Exchange.WebServices.Data.TimeZoneDefinition..ctor(TimeZoneInfo timeZoneInfo)
>    at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.get_TimeZoneDefinition()
>    at FluiTech.CallRouting.Ews.EwsHelper..ctor(EwsOptions options) in C:\dev\BitBucket\FluiTec\CallRouting\src\FluiTech.CallRouting.Ews\EwsHelper.cs:line 59
> --- End of stack trace from previous location where exception was thrown ---
> 

So - something tries to add the id "Dlt/1916" although it's already there.

Again - this happens only for Linux/Ubuntu.

The Exchange-Server i'm using is Exchange2013, if relevant - TimeZone of the linux-server is CET/CEST.

I already found the issue "Trouble with TimeZones" and tried using TimeZoneConverter using the given code:
```
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
		        _service.TimeZoneDefinition.Id = TZConvert.IanaToWindows(_service.TimeZone.Id);
```

Sadly - this only raises the above mentioned exception earlier for me.

**Comment by Robson-Rocha** [comment]
I'm struggling with the same issue. I was previously unadvertetly using the Microsoft.Exchange.WebServices  (non NETStandard) version and the behavior was exactly the same. 

Changing to @sherlock1982 package did not changed the behavior, what makes me think that the problem is indeed due to the way Linux handle with timezone information.

The following code demonstrate the problem:

```
            var exchangeService = new ExchangeService
            {
                Url = new Uri(_exchangeServer),
            };

            NetworkCredential networkCredential = new NetworkCredential(_exchangeUserName, _exchangePassword);

            exchangeService.Credentials = networkCredential;

            DateTime dt1 = DateTime.Parse("2018-01-18T11:32:58Z");
            DateTime dt2 = DateTime.Parse("2018-01-18T11:47:58Z");

            Console.WriteLine(dt1.Kind);

            var meetingRequest = new Appointment(exchangeService)
            {
                Location = "door1",
                Subject = "Meeting in door1",
                Start = dt1,
                End = dt2,
                StartTimeZone = TimeZoneInfo.Local,
                EndTimeZone = TimeZoneInfo.Local,
                Body = new MessageBody { Text ="" },
                ReminderMinutesBeforeStart = 15
            };

            meetingRequest.RequiredAttendees.Add(_meetingRoomId);

            meetingRequest.Save(SendInvitationsMode.SendToAllAndSaveCopy).Wait();
```

Which results in the exception:

> Unhandled Exception: System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: Dlt/1932) ---> System.ArgumentException: An item with the same key has already been added. Key: Dlt/1932
>    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at Microsoft.Exchange.WebServices.Data.TimeZoneTransitionGroup.InitializeFromAdjustmentRule(AdjustmentRule adjustmentRule, TimeZonePeriod standardPeriod)
>    at Microsoft.Exchange.WebServices.Data.TimeZoneDefinition..ctor(TimeZoneInfo timeZoneInfo)
>    at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.get_TimeZoneDefinition()
>    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.WriteToXml(EwsServiceXmlWriter writer)
>    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.<EmitRequest>d__33.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.<BuildEwsHttpWebRequest>d__44.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.<ValidateAndEmitRequest>d__43.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.<InternalExecuteAsync>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.<ExecuteAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Exchange.WebServices.Data.Item.<InternalCreate>d__12.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()

**Comment by svrooij** [comment]
I stumbled onto the same problem.... Same error (on mac). Tried the following combinations:

- Setting the TimeZoneInfo.Local when constructing the `ExchangeService`.
- Setting the TimeZoneInfo.Local when constructing the `ExchangeService` and overriding the `ews.TimeZoneDefinition.Id`.
- Setting the `StartTimeZone` on an appointment.
- Not setting the TimeZone anywhere explicitly.

They all end up crashing. It seems like [Version 1.0.15](https://www.nuget.org/packages/Microsoft.Exchange.WebServices.NETStandard/1.0.15) doesn't have this bug, and that is also compatible with .NET core 2. So for the time being I'll be using that.

**Comment by mackcoding** [comment]
I am having a similar issue. Using the not NETStandard version, I get this error. If I switch to this version, I get NO errors. I'm thinking it might be related. Any updates on the issue?

**Comment by cobells** [comment]
Seeing this same issue as well on OSX.
My specific exception is "An item with the same key has already been added. Key: Dlt/1918"
As svrooij@ mentioned, Version 1.0.15 works fine. I also was able to get master working by changing GetAdjustmentRulesEx in TimeZoneExtensions.cs to just `return new AdjustmentRule[0];`

Just in case it helps in debugging the issue, when I put a breakpoint  in GetAdjustmentRulesEx and inspect tz.GetAdjustmentRules() I see 168 adjustment rules, several of which have the same startDate years (thus the collision when using those years to get key names)

**Comment by dmitryanufriev** [comment]
With small fixes from PR #33 works as expected. Would PR #33 be accepted?

**Comment by jbennink** [comment]
Since you closed this on 2022-09-15 and the nuget package currently available is dated 2022-09-07 I assume this fix is not in the current 2.0.0-beta3 package? So to get this I have to build from source

I am lso notcing thet the repo project still says beta2!

**Comment by ststeiger** [comment]
Correct. 
I have no nuget released for my repo. 
And sherlock's version doesn't contain this fix.

**Comment by ststeiger** [comment]
@jbennink: 
Take the source from here:
https://github.com/OfficeDevUnofficial/ews-managed-api
