### ISSUE TITLE
Methods not accepting CancellationToken

### ISSUE THREAD

**Issue by zorgoz** [sherlock1982/ews-managed-api#17]
Hello!
Great job you have done here! Unfortunately, none of the methods is accepting CancellationToken parameter (has no overload accepting such parameter) whilst this is almost standard in the async approach. I know that these operations last quite short, thus this is not a blocking condition, but it would be a great feature to add... Do you have such intention?

**Comment by sherlock1982** [comment]
Yes it's a nice idea. For now as a workaround you can use external cancellation

**Comment by zorgoz** [comment]
What do you mean by _external cancellation_?

**Comment by sherlock1982** [comment]
There are lots of async functions which doesn't accept CancellationToken. Though you're still able to cancel them like this:

        public static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)
        {
            var tcs = new TaskCompletionSource<bool>();
            using (cancellationToken.Register(
                        s => ((TaskCompletionSource<bool>)s).TrySetResult(true), tcs))
                if (task != await Task.WhenAny(task, tcs.Task))
                    throw new OperationCanceledException(cancellationToken);
            return await task;
        }

Just call it like that:

    ReadAsync().WithCancellation(token);

Yes it will not really cancel undergoing procedure but it's the only way to do something about it.

**Comment by zorgoz** [comment]
Ok, thank you!

**Comment by sherlock1982** [comment]
The issue with cancellation token is that inside the library is using WebRequests. Which doesn't support cancellation. So actually even if I will add it to interface it will not really cancel until I change to System.Net.Http.
