### ISSUE TITLE
Empty Attachment Content Size in Version 1.1.1

### ISSUE THREAD

**Issue by jenskabella** [sherlock1982/ews-managed-api#19]
We have a Problem with the ews-managed-api.

If we use the GetAttachments Function the Size and the Content of the Attachment ist empty.

`var exchangeResponse = ExchangeService.GetAttachments(new[] { attachmentId }, null, PropSet);
var ewsAttachmentResponse = exchangeResponse.Result.First();
var ewsAttachment = ewsAttachmentResponse.Attachment;`

How can I Load the Content and Size for an MemoryStream?

**Comment by darkhck** [comment]
Hi!
Here is my code. Maybe it will help.

foreach (Item item in findResults.Items)
{
    if(item.HasAttachments)
    {
        EmailMessage message = await EmailMessage.Bind(service, item.Id, new PropertySet(BasePropertySet.IdOnly, ItemSchema.Attachments));
        foreach (Attachment attachment in message.Attachments)
        {
            FileAttachment fileAttachment = attachment as FileAttachment;
            await fileAttachment.Load();

            FileStream fs = new FileStream(dataPath + "some.csv", FileMode.Create, FileAccess.ReadWrite);
            fs.Write(fileAttachment.Content, 0, fileAttachment.Content.Length);
            fs.Close();
            fs.Dispose();
        }
    }
                
}

**Comment by jenskabella** [comment]
Thank you for your feedback.It helped. 

But it seems that there was a bug in Version > 1.1.0. As we switched back to 1.1.0 we don´t have to use the FileStream. Maybe there is a Bug?
