### ISSUE TITLE
File Attachment 0 bytes

### ISSUE THREAD

**Issue by mosespaez** [sherlock1982/ews-managed-api#2]
Having problem when retrieving the attachment, getting 0 bytes.
Below is the code snippet,

```
foreach (Item item in _findResults)
                {                  
                    EmailMessage message = EmailMessage.Bind(serviceInstance, item.Id, new PropertySet(BasePropertySet.IdOnly, ItemSchema.Attachments)).Result;
                    foreach (Attachment _attachment in message.Attachments)
                    {
                        if (_attachment is FileAttachment)
                        {
                            FileAttachment fileAttachment = _attachment as FileAttachment;
                            fileAttachment.Load();
                            byte[] result;

                            using (var streamReader = new MemoryStream())
                            {
                                fileAttachment.Load(streamReader);
                                streamReader.Seek(0, SeekOrigin.Begin);
                                result = streamReader.ToArray();
                            }

                        }
                    }                  
                }
```

**Comment by mikes-gh** [comment]
Same here.

**Comment by mikes-gh** [comment]
The answer is the Load methods are calling a void async methods.
I had to add a `.Wait()` int the following places other wise Load return before the service object has the data.

https://github.com/sherlock1982/ews-managed-api/blob/master/Core/ExchangeService.cs#L1833
https://github.com/sherlock1982/ews-managed-api/blob/master/Core/ServiceObjects/Items/Item.cs#L147

**Comment by sherlock1982** [comment]
I will check it as soon as possible.

**Comment by mikes-gh** [comment]
Actually I camer up with a better solution.
I made all the Load methods return a Task.

Then you can use the Load Methods with Wait or use async methods.

I will send a PR as a WIP so you can review

**Comment by mikes-gh** [comment]
@sherlock1982 I added a PR so you can see what I mean

**Comment by sherlock1982** [comment]
Yes, thank you. These issues appeared when I moved to async. Unfortunately VS doesn't give warnings on these situations.

**Comment by mikes-gh** [comment]
> unfortunately VS doesn't give warnings on these situations.

You can use these for async analysis
https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers
I also recommend 
https://github.com/DotNetAnalyzers/StyleCopAnalyzers

This gives you xplat code analysis in vscode aswell as vs.
