### ISSUE TITLE
Issue running on Ubuntu 14.04 with .net core 2.1

### ISSUE THREAD

**Issue by ymor** [sherlock1982/ews-managed-api#25]
It looks like with the new socket changes in .Net core 2.1 the HttpWebRequest and HttpWebResponse are no longer supported on Unix.  As i get the following error: No support for channel binding on operating systems other than Windows. 
Are there any plans to move all requests/responses to use the HttpClient?  At the moment I've worked around this be adding the following to my code: AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false); which set it back to the 2.0 implementation.

Thanks.

**Comment by sherlock1982** [comment]
Thanks for reporting it! I have plans to move to HttpClient though it needs to be tested a lot.
