### ISSUE TITLE
Attachments Download

### ISSUE THREAD

**Issue by sav68** [sherlock1982/ews-managed-api#31]
Hi everybody
Is any problem with download attachments in .net core 2?
I trying to download the attachments but when they save, they have 0 size.
can you help me?

Thanks in advance
this is my code

FindItemsResults<Item> Results = _service.FindItems(WellKnownFolderName.Inbox, new ItemView(1)).Result;
            foreach (Item item in Results.Items)
            {
                EmailMessage msg = EmailMessage.Bind(_service, item.Id, new PropertySet(BasePropertySet.FirstClassProperties)).Result;

                if (msg.IsRead == false)
                    model.Add(new ExchangeMailTemplateModel
                    {
                        Subject = msg.Subject,
                    });

                msg.Load(new PropertySet(EmailMessageSchema.Attachments));
                if (msg.HasAttachments)
                {
                    foreach (var attachment in msg.Attachments)
                    {
                        if (attachment is FileAttachment)
                        {
                            FileAttachment fileAttachment = attachment as FileAttachment;
                            fileAttachment.Load();

                            fileAttachment.Load("C:\\temp\\" + fileAttachment.Name);
                            using (FileStream theStream = new FileStream("C:\\temp\\Stream_" + fileAttachment.Name, FileMode.OpenOrCreate, FileAccess.ReadWrite))
                            {
                                fileAttachment.Load(theStream);
                            }
                            Console.WriteLine("FileName: " + fileAttachment.FileName);
                        }
                        else
                        {
                            ItemAttachment itemAttachment = attachment as ItemAttachment;
                            itemAttachment.Load(ItemSchema.MimeContent);
                            string fileName = "C:\\Temp\\" + itemAttachment.Item.Subject + ".eml";
                            // Write the bytes of the attachment into a file.
                            File.WriteAllBytes(fileName, itemAttachment.Item.MimeContent.Content);
                            Console.WriteLine("Email attachment name: " + itemAttachment.Item.Subject + ".eml");
                        }
                    }
                }
            }

**Comment by KyleCraviotto** [comment]
Here's what I had to do to get this to work
case FileAttachment fa:
                        try
                        {
                            await fa.Load();
                            using (var ms = new MemoryStream(fa.Content))
                            {
                                var fileLocation = await SaveAttachmentFile(ms, path, fa.FileName ?? fa.Name);
                                renameResults.Add(attachment.ContentId ?? attachment.Name, fileLocation);
                            }
                        }
                        catch (Exception ex)
                        {
                            _logger.LogWarning(ex, $"Something went wrong saving File Attachment {fa.FileName ?? fa.Name}");
                        }
                        break;
                    case ItemAttachment ia:
                        try
                        {
                            // Load Item with additionalProperties of MimeContent
                            await ia.Load(ItemSchema.MimeContent);
                            // MimeContent.Content will give you the byte[] for the ItemAttachment
                            // Now all you have to do is write the byte[] to a file
                            if (ia.Item != null)
                            {
                                using (var ms = new MemoryStream(ia.Item.MimeContent.Content))
                                {
                                    var fileName = ia.Name + ".eml";
                                    var fileLocation = await SaveAttachmentFile(ms, path, fileName);
                                    renameResults.Add(attachment.ContentId ?? attachment.Name, fileLocation);
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            _logger.LogWarning(ex, $"Something went wrong saving File Attachment {ia.ContentId ?? ia.Name}");
                        }
                        break;
                }
