### ISSUE TITLE
Content Type issue

### ISSUE THREAD

**Issue by sjzamora86** [sherlock1982/ews-managed-api#32]
Hi Guys,

I'm having some issue when I tried to use this version with relates to the content type.
Is there anyone has the same issue? Your help is very much appreciated. Thanks!

`Inner Exception 1:
ServiceRequestException: The request failed. Cannot process the message because the content type 'text/plain; charset=utf-8' was not the expected type 'text/xml; charset=utf-8'.

Inner Exception 2:
EwsHttpClientException: Cannot process the message because the content type 'text/plain; charset=utf-8' was not the expected type 'text/xml; charset=utf-8'.`

**Comment by sherlock1982** [comment]
What's the request? Is it on beta? I havent't finished this part yet - you can try 1.x

**Comment by sjzamora86** [comment]
I'm using 2.0.0-beta1 version.

**Comment by sherlock1982** [comment]
Any small sample to reproduce?

**Comment by sjzamora86** [comment]
It is working in 1.x version but I'm having different issue in TimeZone running Linux. But for your reference this is the code that I'm running when I hit this error using version 2.x

AvailabilityOptions availabilityOptions = new AvailabilityOptions()
    {
        MeetingDuration = 40,
        RequestedFreeBusyView = FreeBusyViewType.FreeBusy,
        DetailedSuggestionsWindow = new TimeWindow(startDate, endDate)
    };

    GetUserAvailabilityResults results = service.GetUserAvailability(attendees,
        availabilityOptions.DetailedSuggestionsWindow,
        AvailabilityData.FreeBusy,
        availabilityOptions).Result;

**Comment by LubosVoska** [comment]
I have same error.

`<PackageReference Include="Microsoft.Exchange.WebServices.NETStandard" Version="2.0.0-beta1" />
`

And error ocurs when try find items.

`var result = exchange.FindItems(WellKnownFolderName.Inbox, view).Result;
`

**Comment by yassinebennani** [comment]
I have the same issue
<PackageReference Include="Microsoft.Exchange.WebServices.NETStandard" Version="2.0.0-beta1" />
And error ocurs when I try
CalendarFolder calendar = await CalendarFolder.Bind(this.Service, WellKnownFolderName.Calendar, new PropertySet());

**Comment by ScarletKuro** [comment]
@sherlock1982 have the same problem, any idea how to solve this?

**Comment by sherlock1982** [comment]
Sorry, guys. Just didn't have time to do it. Don't use beta. Please use last version which is not beta.

**Comment by sherlock1982** [comment]
This is fixed in 2.0.0-beta2
