### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by flecce** [sherlock1982/ews-managed-api#35]
Hi,

the .NET framework 4.6.1 Windows Form application returns this error:
**A strongly-named assembly is required.**

Nuget package dependencies says: .NETFramework,Version=v4.6

What am I doing wrong?
Thanks in advance

**Comment by afterlogic-support** [comment]
+1

Not having a strong name for this assembly causes some trouble in various scenarios. Would be great if the assembly becomes strong-named.
