### ISSUE TITLE
Net Core 2.0.0 support?

### ISSUE THREAD

**Issue by mikes-gh** [sherlock1982/ews-managed-api#5]
What do you think about a netcore 2.0.0 version using  new project system.
You don't need VS 2017 as vscode and `dotnet migrate` are sufficient to build.
I haven't tried 2.0.0 yet but will be moving quite soon after RTM as the API surface is dramatically increased.
Will probably be able to enable some more features on Linux.

**Comment by sherlock1982** [comment]
Yes it's a nice idea. I think we will switch to 2.0.0 after the release and approximately in autumn I will change a build system.
