### ISSUE TITLE
An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'

### ISSUE THREAD

**Issue by peterYong** [sherlock1982/ews-managed-api#51]
When I write code in .net core 3.0 to get the folder through exchange, there is no problem when running on windows, but the following error is returned when running on linux：
System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'

**Comment by sherlock1982** [comment]
Please install gss-ntlmssp. 
For example on Debian it will be: "apt-get install gss-ntlmssp"

**Comment by tjmoore** [comment]
I've just hit this myself and yet I'm only specifying NetworkCredentials with username & password with email for username. I wasn't expecting it to try NTLM.

Installing the package fixes it, but there's an issue on the platform I'm targeting in that we may be unable to install that.
