### ISSUE TITLE
Unable to save new appointment

### ISSUE THREAD

**Issue by PlsNoticeMeSenpai** [sherlock1982/ews-managed-api#8]
Hi Nikolai!

I've tried to save new appointment (nothing special, just creating new appointment with few fields like Subject/Location/Start/End/Attendees) and got a lot of exceptions (please check screenshots below). 

            

            Appointment meeting = new Appointment(service);

            meeting.Subject = "Subject";
            meeting.Body = "Body";
            meeting.Start = DateTime.Now.AddHours(2);
            meeting.End = DateTime.Now.AddHours(4);
            meeting.Location = "Location";
            meeting.RequiredAttendees.Add("email@example.com");
            meeting.ReminderMinutesBeforeStart = 30;

            meeting.Save(SendInvitationsMode.SendToNone); 

I've tried to investigate the issue but didn't find any solutions to fixing that on saving (not on retrieving).
Also I've checked code from MSDN and it's exactly the same...

Could you please point out what I'm doing wrong? Or it is known issue? 

Thanks!

![2017-07-25 15_26_00-consoleapp3 debugging - microsoft visual studio](https://user-images.githubusercontent.com/15312989/28571993-e6a05436-714d-11e7-9c9e-1cdd4245648c.png)

**Comment by sherlock1982** [comment]
Well it's not an issue. An appointment is really created by your code. And it's absolutely correct that appointment fields throw exception because they were not read. Though you have the most important field: ID.

To access created appointment data do something like this (or modify accordingly for async/await)

            meeting.Save(SendInvitationsMode.SendToNone).Wait();
            var appointment = Appointment.Bind(service, new ItemId(meeting.Id.UniqueId)).Result;

**Comment by PlsNoticeMeSenpai** [comment]
Thanks for the answer!

I've tried your solution, but appointment still isn't saving, .Save() method throws exception :( 

Seems that there is something wrong with timezones (I've tried to init service with/without timezone, same result)

![2017-07-27 08_09_31-consoleapp3 debugging - microsoft visual studio](https://user-images.githubusercontent.com/15312989/28655258-2c47fe98-72a3-11e7-83af-1a73fcb3c9fc.png)

**Comment by sherlock1982** [comment]
Please use the latest version. This exception was fixed in some of the releases
